pfresgo:
  branch: BP
  benchmark_protocol: standard
  evaluation_space: benchmark
  branch_go_ids_path: /workspace/data_pfresgo/processed/go_ids_bp.json
  go_text_path: /workspace/data_pfresgo/processed/go_texts_canonical_segmented.jsonl
  test_ids_path: /workspace/stargo/datasets/pfresgo/test.txt
  evaluation_split: test
  rare_lt: 20
  enabled_segments:
    - name
    - definition
    - is_a
data:
  overlap: 256
  max_len: 1024
  use_dag_in_ds: false
  fs_target_ratio: 0.0
general:
  phase: -2
  ablation_id: PFresGO-BP-RetrieverV2-FullGO-PBR
  go_pooling_strategy: mean
  go_encoder_inner_pooling: mean
  go_pool_type: mean
  go_encoder_output_mode: segment_pooled
  go_segment_representation_mode: segments_only
  protein_pooling_strategy: mean_attn_gate
  use_lora: false
  use_attribution_loss: false
  return_alpha: false
training:
  epochs: 15
  batch_size: 4
  eval_batch_size: 4
  num_workers: 0
  fp16: true
  cpu: false
  seed: 42
  output_dir: /workspace/data_pfresgo/outputs/bp/retriever_v2_fullgo_pbr
  save_every: 1000000 #10000
  keep_last_n: 3
  resume: /workspace/data_pfresgo/outputs/bp/retriever_v2_fullgo_pbr/checkpoint_step88215.pt
  warmstart_path: null
  eval_only: true
  log_every: 500
  log_level: INFO
  monitor_metric: oracle_microF@500
  secondary_monitor_metric: macro_term_recall@500
  monitor_mode: max
  early_stop_patience: 3
  eval_go_bs: 256
  go_text_store_max_len: 128
  go_segment_max_len: 64
  go_token_dropout: false
  go_pooling: none
optim:
  lr: 1.0e-05
  weight_decay: 0.0
  grad_clip: 1.0
model:
  align_dim: 768
  temperature: 0.07
  attn_heads: 2
  attn_dropout: 0.1
loss:
  lambda_con: 1.0
  pbr_lambda: 0.001 # %10 #0.0
  pbr_margin: 0.05
  pbr_tau: 0.05
evaluation:
  retrieval_eval_ks:
    - 50
    - 100
    - 200
    - 500
    - 1000
  positive_rank_quantiles:
    - 0.5
    - 0.75
    - 0.9
    - 0.95
diagnostics:
  log_gradient_norms: true
  log_positive_rank_cdf: true
  log_cardinality_metrics: true
  log_go_segment_weights: true
wandb:
  enabled: true
  project: protein-go-align-pfresgo
  entity: null
  wandb_run_name: PFresGO-BP-RetrieverV2-FullGO-PBR
  mode: online
stores:
  train_ids_path: /workspace/stargo/datasets/pfresgo/train.txt
  val_ids_path: /workspace/stargo/datasets/pfresgo/valid.txt
  go_basic_json: /workspace/data_pfresgo/processed/go_vocab.json
  pid2pos_path: /workspace/data_pfresgo/processed/pid_to_positives_bp.json
  zero_shot_path: null
  few_shot_path: null
  go_path_seen: null
  go_path_observed: null
  embed_dir_res: /workspace/data_pfresgo/protein_embeddings/esm1b_residue
  go_text_folder: /workspace/data_pfresgo/processed
  go_cache_path: /workspace/data_pfresgo/go_cache/all/go_text_embeddings_canonical.npy
  seq_len_lookup: /workspace/data_pfresgo/processed/seq_len_lookup.pkl
  logs: /workspace/data_pfresgo/logs/retriever_v2_fullgo_pbr
