data:
  overlap: 256
  max_len: 1024
  no_cache_shards: false

  # DAG & expansion
  use_dag_in_ds: true
  min_pos_for_expand: 3
  max_ancestor_add: 4
  max_hops: 3
  ancestor_gamma: 0.7

  # Few/Zero-shot
  fs_target_ratio: 0.3

general:
  use_queue_miner: True
  use_go_memory_bank: True
  use_faiss: False

memory_bank:
  device: "cuda"
  dtype: "fp16"

caches:
  go_cache: null
  faiss_index: null

  go_cache_template: /workspace/cache/go_cache_phase{phase}.pt
  faiss_template: /workspace/cache/faiss_phase{phase}.index

training:
  epochs: 5
  batch_size: 4
  eval_batch_size: 4
  device: "cuda:0"

  num_workers: 8
  val_num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2

  fp16: true
  cpu: false
  seed: 42

  output_dir: /workspace/protein-go-align/outputs/run
  save_every: 2000
  keep_last_n: 3
  resume: null
  log_every: 500
  log_level: INFO
  monitor_metric: "cafa_fmax"   # "total" da olabilir
  monitor_mode: "max"           # "min" (ör. total loss) için değiştir
  early_stop_patience: 3        # 0 veya negatif => kapalı
  cand_chunk_k: 2048
  pos_chunk_t: 64
  k_hard_queue: 64
  queue_K: 65536

optim:
  lr: 0.0003
  weight_decay: 0.01
  grad_clip: 1.0

model:
  align_dim: 768
  temperature: 0.07
  attn_heads: 2
  attn_dropout: 0.1
  entropy_reg: 0.01
  win_size: 1024
  win_stride: 256

loss:
  lambda_con: 1.0
  lambda_dag: 0.2
  lambda_attr: 0.0
  dag_margin: 0.05
  dag_scale: 10.0
  lambda_vtrue: 0.0
  tau_distill: 1.5

curriculum:
  epochs: 4
  warmup_frac: 0.1
  mode: cosine
  hard_frac: [0.2, 0.7]
  shortlist_M: [128, 64]
  k_hard: [4, 1]
  hier_up: [1, 0]
  hier_dn: [0, 0]
  random_k: [4, 0]
  inbatch_easy: [1.0, 0.0]
  neg_k: 8
  curriculum_mode: cosine

schedule:
  phase_breaks: [5, 12, 25]
  stageA_mix: [1.0, 0.0, 0.0]
  stageB_mix: [0.7, 0.3, 0.0]
  stageC_mix: [0.4, 0.4, 0.2]
  stageD_mix: [0.4, 0.4, 0.2]
  lambda_attr_start: 6
  lambda_attr_max: 0.2

wandb:
  enabled: true
  project: protein-go-align
  entity: null
  run_name: null
  mode: online

stores:
  train_ids_path: /workspace/data/training_ready/proteins/protein_train_ids.txt
  pid2pos_path: /workspace/data/training_ready/proteins/pid_to_positives.json
  val_ids_path: /workspace/data/training_ready/proteins/protein_val_ids.txt

  embed_dir: /workspace/esm_output #ESM3b
  embed_dir_res: /workspace/protein/residues
  embed_dir_fused: /workspace/protein/fused
  hub_local_dir: /workspace/.cache/huggingface/hub

  seq_len_lookup_dir: /workspace/data/training_ready/proteins/seq_len_lookup.pkl
  protein_manifest_file: /workspace/data/training_ready/manifest_cache/esm_manifest.pkl

  output_dir: /workspace/protein-go-align-outputs
  logs: /workspace/protein-go-align-logs

  go_text_folder: /workspace/data/processed/go_terms/go_phases